{% set version = "1.6.1" %}

package:
  name: plio
  version: {{ version }}

source:
  url: https://github.com/USGS-Astrogeology/plio/archive/{{ version }}.tar.gz
  sha256: b409e8122ea382e95d06d17c257b7b71598df496b1168f9dc6612e67b0dc38e3
  patches:
    - 0000-use-console-scripts.diff
    - 0001-Fixes-Protobuf-compatability-issues-217.patch

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python
  entry_points:
    - socetnet2isis = plio._cli.socetnet2isis:__main__
    - isisnet2socet = plio._cli.isisnet2socet:__main__


requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - numpy
    - pvl >=1.0
    - protobuf >=4,<5
    - pandas
    - sqlalchemy
    - pyyaml
    - affine
    - networkx
    - h5py
    - scipy
    - setuptools
    - pyproj
    - jinja2
  run_constrained:
    - gdal

test:
  requires:
    - pip
  imports:
    - plio

  commands:
    - pip check
    - socetnet2isis --help
    - isisnet2socet --help

about:
  home: http://github.com/USGS-Astrogeology/plio
  license: CC0-1.0
  license_file: LICENSE.md
  summary: input/output library for planetary science data

extra:
  recipe-maintainers:
    - jlaura
    - acpaquette
    - kelvinrr
