appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: efxozKZvJSOCevv6ffRoloDbQ5OxjFK8J5A6iKkAAUm0kzORrN3nfkV8+QwSA//fkL9OAKdPgF9FN9QR8+Nq6RhEqWI3USZOCe1q0L6wLmqlshyC2TBU3+4PhMcEDLkpFEKPmsxvNI7rP0gpv+0rkdAui1rTS6+Ta60oDuMa1yyB5nfwp58mSKzr/n7dxFwznZYPTy05mhHBh+/8jdgLGfNoXIEvVZSw46qIwsa8KjkDNouIdSEuvdT19QRK16rE4Cu9V+yzLGizuwoh0HlNnqiJgqHuUsXLUoU8pY4eQoYuECUqwRuj2pDc4vjLc0Cs6aTw/Zq/oyVfiRgoS8hZ/XWY5vO5PgUWOxlC9JO7PB1aVgIVU1Z0DrlL6qwQMqBMccAY7N9jfQ399AFyDirEFoXWyvNVu8kQ4NzZm1wVKr8WE79yBZfwp4JzADNKMtD11H574KblFYjz2VIGls1VIlHk9vCnDwTuBBMgGQhYaFFdiWupQxe6NKdVIZuKFC6KCFVbMOnr9/UVazROOxEsGJ/E6vedxHI3IZCU6LHFUM1rNdEQiMJ2rZhzkPTr8CFxyfpwCO94/OY5CWVNwMSo27QAs1Eym5yXzyMK9s8BC7ENFgKh8J1rr39O+cumiyC1Edx7y2i4emn9GpS/iFrPiaBCm8UfrztSaEvpaUo8tso=}
provider:
  win: azure
conda_forge_output_validation: true
